networks:
  appnet:
    driver: bridge
    external: true

services:
  backend:
    container_name: cbt-backend

    build:
      context: ./backend
      dockerfile: ./dockerfile

    ports:
      - "8080:8080"

    volumes:
      - ./backend/logs/log_backend.log:/app/logs/log_backend.log:rw
