[tool.poetry]
name = "app"
version = "0.1.0"
description = "CBT web-application"
authors = ["Vadim Kuleshov <merulis@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.114.2"
uvicorn = "^0.30.6"
httpie = "^3.2.3"
pytest = "^8.3.3"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = "^1.7.4"
python-multipart = "^0.0.12"
pydantic = {extras = ["email"], version = "^2.9.2"}
httpx = "^0.27.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
