"""add column passhash to User table

Revision ID: 3faa676f4c54
Revises: 6aaf173381b6
Create Date: 2024-10-22 12:45:34.519045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3faa676f4c54"
down_revision: Union[str, None] = "6aaf173381b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activity", sa.Column("category", sa.String(), nullable=False))  # noqa
    op.drop_column("activity", "type")
    op.add_column("user", sa.Column("passhash", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "passhash")
    op.add_column(
        "activity", sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False)
    )  # noqa
    op.drop_column("activity", "category")
    # ### end Alembic commands ###
