"""add relation User only -> many Activity

Revision ID: 6ce7a3a446a2
Revises: 338a01657b90
Create Date: 2024-10-16 12:07:20.437904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ce7a3a446a2"
down_revision: Union[str, None] = "338a01657b90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "activity", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "activity", type_="foreignkey")
    op.drop_column("activity", "user_id")
    # ### end Alembic commands ###
